#!/bin/sh
#
# You have to install this file before committing:
#   ln -s ../../pre-commit .git/hooks/pre-commit
#

# Save all changes in working tree.
STASH_NAME=$(git stash create)

# Reset working tree to index.
git checkout .

# Check if formatting is correct.
if ! crystal tool format --check; then
  crystal_format_error=true
fi

# Store unstaged changes and exit with error if formatting is not correct.
if [ -n "$crystal_format_error" ]; then
  echo -e "\e[33;1;3mPlease run 'crystal tool format' before committing.\e[0m"

  git stash store "$STASH_NAME"
  echo -e "\e[32;1;3mUnstaged changes are stashed. \e[39mYou can recover them with \e[34mgit stash pop\e[39m after correcting the formatting.\e[0m"

  exit 1
fi

# If formatting is correct, but there were unstaged changes, recover them.
if [ -n "$STASH_NAME" ]; then
  git stash apply -q "$STASH_NAME"
fi
