import:
  - spec/configs/imported0.yaml
  - spec/configs/imported1.yaml

import_main:
  command:
    echo "OK from import_main"
  depends_on:
    - imported0
    - imported1
    - import0

import0:
  command:
    echo "OK from import0"
