output:
  commands:
    - echo "The result is $RESULT"
  depends_on:
    -
      job: run_crystal
      env: RESULT
    - job: just_echo2
    - just_echo

run_crystal:
  commands:
    - crystal eval "puts 1 + 3"

just_echo:
  commands:
    - echo "I'm echo"

just_echo2:
  commands:
    - echo "I'm second echo"
